import type { Metadata } from "next";
import "./globals.css";
import localFonts from "next/font/local";
import Footer from "./Footer";

const zodiak = localFonts({
  src: [
    {
      path: "../public/fonts/Zodiak/Zodiak-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Zodiak/Zodiak-Extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Zodiak/Zodiak-Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-zodiak",
  fallback: [
    "serif",
    "ui-serif",
    "Georgia",
    "Cambria",
    "Times New Roman",
    "Times",
  ],
});

const jakarta = localFonts({
  src: [
    {
      path: "../public/fonts/PlusJakartaSans/PlusJakartaSans-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/PlusJakartaSans/PlusJakartaSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PlusJakartaSans/PlusJakartaSans-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/PlusJakartaSans/PlusJakartaSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/PlusJakartaSans/PlusJakartaSans-Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-jakarta",
  fallback: [
    "sans-serif",
    "ui-sans-serif",
    "Helvetica Neue",
    "Arial",
    "Noto Sans",
    "Liberation Sans",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Noto Color Emoji",
  ],
});

export const metadata: Metadata = {
  title: "Ironleaf Atelier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zodiak.variable} ${jakarta.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
